### ISSUE TITLE
Splunk HEC Exporter Integration for Grafana Alloy

### ISSUE THREAD

**Issue by PatMis16** [grafana/alloy#1226]
### Request

This document proposes the addition of a feature that enables Grafana Alloy to forward logs directly to a Splunk instance using the Splunk HTTP Event Collector (HEC) protocol. This functionality would be achieved by integrating the Splunk HEC exporter from the [OpenTelemetry Collector Contrib Repository](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/splunkhecexporter) into Grafana Alloy.

### Use case

Many organizations, including ours, leverage Splunk as their primary log management solution. Currently, Grafana Alloy lacks a native way to send collected logs directly to Splunk. This necessitates workarounds, such as deploying a separate log forwarder. These workarounds introduce additional complexity, potential points of failure, and hinder a streamlined observability experience.

The proposed integration with the Splunk HEC exporter would address these challenges by providing the following benefits:

- **Simplified Log Forwarding:** Eliminates the need for a separate log forwarder, streamlining data flow and reducing operational overhead.
- **Improved Efficiency:** Enables direct communication between Grafana Alloy and Splunk, potentially enhancing data transfer speed and reducing latency.
- **Enhanced User Experience:** Provides a more unified observability experience by allowing users to manage log collection and forwarding within Grafana Alloy.

### Technical Considerations
- The integration should leverage the existing Splunk HEC exporter from the OpenTelemetry Collector Contrib Repository.
- Configuration options within Grafana Alloy should allow users to specify:
  - Splunk HEC endpoint URL
  - Splunk HEC token
  - Relevant TLS settings (if applicable)
- Error handling and logging mechanisms should be implemented to ensure proper feedback for troubleshooting purposes.

### Future Considerations
- Explore potential integrations with other popular log management solutions beyond Splunk.
- Investigate the feasibility of supporting additional data formats beyond logs (e.g., metrics) through the Splunk HEC exporter.

### Conclusion
Integrating the Splunk HEC exporter into Grafana Alloy would significantly improve the platform's log forwarding capabilities. This feature would streamline data flow, enhance user experience, and improve overall observability within the Grafana ecosystem. We believe this integration aligns with Grafana's commitment to providing a comprehensive and user-friendly observability platform.

**Comment by ptodev** [comment]
Hi, @PatMis16! Thank you for opening this issue. We could certainly add a new `otelcol.exporter.splunkhec` component. My only concerns with adding any new components is simply the maintenance cost. It takes effort to upgrade OTel in Alloy since we have to review OTel's changelog manually and make sure we're using the latest features.

To gauge how much maintenance a component requires, I usually check a few things:
* Whether the config is very complex. The splunkhecexporter's [config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/splunkhecexporter/config.go) is not super simple, but I wouldn't say it's complicated either. It'd be a few hours of effort to incorporate it.
* Whether the documentation is very long. In [this case](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/splunkhecexporter/README.md), it is not.
* Whether the component changes frequently. This could increase the cost of maintaining it. I had a look at the past few Contrib releases, and it seems `splunkhecexporter` exporter is relatively stable. It doesn't seem to change a lot in major ways.
* Whether we (the Alloy maintainers) dogfood the component. In this case we aren't able to do that, but as long as our wrapper around OTel is thin or as long as we have some community support (e.g. from yourself 😊) then that's not an issue.

Based on this, I'd say it's completely doable to have an `otelcol.exporter.splunkhec` component.

May I ask a few more questions please:
* Would you be interested in submitting the initial PR?
* Would you be interested in "owning" the component as a [community component](https://grafana.com/docs/alloy/latest/get-started/community_components/)? The concept of "community components" is a recent one, which we created so that we could incorporate a [DataDog exporter](https://github.com/grafana/alloy/pull/739). That PR hasn't been merged yet, so at the moment we still don't have any community components. In practice, I suppose most of the workload would consist of submitting the initial PR, and occasionally helping out in related discussions. The component seems pretty stable, so probably there's no need for community involvement during OTel upgrades. There is also a [doc](https://github.com/grafana/alloy/blob/main/docs/developer/adding-community-components.md) regarding adding community components in the Alloy repo.

It is ok if you're not able to submit the initial PR or to assume ownership of the community component, but it'd mean that the work gets prioritised a little later. We will need to check further regarding prioritisation, because I'm not sure what the priority of this request vs other ones is.

In the long term, I hope we can automate most of this maintenance work. WIP features such as [OTel config schema](https://github.com/open-telemetry/opentelemetry-collector/pull/10694) could autogenerate code and documentation. This could significantly reduce the need for community component ownership.

**Comment by PatMis16** [comment]
@ptodev 
Hi, yes I think I can do that. Can you explain or are there any ressources which explain how thiw with the "ownership" works and what is expected of the "owner"? 
BR,
Patrick

**Comment by PatMis16** [comment]
@ptodev 
Hi,
What must be done for the initial PR? 
Thanks,
Patrick

**Comment by PatMis16** [comment]
Created Pull Request https://github.com/grafana/alloy/pull/1645

**Comment by RalfWenzel** [comment]
Hi @ptodev , @PatMis16 

are u currently working on the issue? I'm very intested in this and would also be able to contribute if help is required either with coding or docs. 
My skills here: 
- Splunk/HEC -> expert (i've written a couple of integrations/api-wrappers , most of them c# but currently migrating to go)
- Alloy -> advanced beginner (currently migrating customers from otel-contrib to alloy, thats why i'm interested in this)

**Comment by ptodev** [comment]
Hi, @RalfWenzel 👋  This component was merged via #1885 and it'll be available in v1.6 as [otelcol.exporter.splunkhec](https://grafana.com/docs/alloy/next/reference/components/otelcol/otelcol.exporter.splunkhec/). Alloy v1.6 will be released on 2025-01-08.

@PatMis16 Apologies, I never got around to replying to you above! I'm happy that the work progressed regardless.

I'll close this issue now that the component has been merged.
