### ISSUE TITLE
When will you cut a new release since v1.2.1 contains a critical vuln CVE-2024-41110 which it looks like fixed in the main branch?

### ISSUE THREAD

**Issue by developer-guy** [grafana/alloy#1404]
### Request

Vuln scanners reported a critical CVE in grafana alloy v1.2.1 about:

- github.com/docker/docker               v25.0.5+incompatible     26.1.4    go-module  GHSA-v23v-6jw2-98fq  Critical

which is seem to fix in the main branch https://github.com/grafana/alloy/blob/main/go.mod#L32 

so as I don't know the release schedule, are you going to cut a new release soon to fix this CVE?

Thank you

### Use case

to fix a CVE

**Comment by thampiotr** [comment]
The v1.3.0 should be coming within the next week. You can see release [cadence here](https://github.com/grafana/alloy?tab=readme-ov-file#release-cadence). For questions in the future, please [use Slack or our community site](https://github.com/grafana/alloy?tab=readme-ov-file#community), because we use GitHub issues for bugs and feature requests rather than questions, thanks!

**Comment by developer-guy** [comment]
ah thank you, sorry about that, I didn't notice that earlier!
