### ISSUE TITLE
Drop FreeBSD support? 

### ISSUE THREAD

**Issue by wildum** [grafana/alloy#1529]
FreeBSD is not supported by the Otel collector. As an Otel distribution, it makes sense to align on the platforms that Otel supports, or else we end up making build exceptions for components that bring dependencies that are not supported on FreeBSD (for example: datadog exporter).

On this day, the number of reported Alloy instances running on FreeBSD is very small. 

Update: given the community feedback + the fact that so far we can make easy exceptions for the components where it breaks, we can try to keep it as long as possible

**Comment by 1992kk** [comment]
We also plan on using Grafana Alloy instead of building Otel collector as an agent as it supports FreeBSD(lot of hosts) natively.

**Comment by wildum** [comment]
The decision is not final and the next major release is still far in the future. It will depend on how much effort it is to keep it and how many people want us to keep it

**Comment by skip2networks** [comment]
We're working on deploying Alloy at scale on FreeBSD-based systems. +1 for keeping FreeBSD.

**Comment by ptodev** [comment]
Adding build exceptions for components that don't work with FreeBSD doesn't sound like a lot of effort. If that's all we need to do, IMO we can keep the FreeBSD builds.

**Comment by siepkes** [comment]
Perhaps it is possible to keep support for FreeBSD and mark it as a "Tier 2" or "non-supported" platform? By showing a warning in the documentation and when starting the application?

Dropping FreeBSD support basically means not supporting anything which isn't Linux, macOS or Windows. Because FreeBSD is the most well supported of all non-Linux *nix'es. If FreeBSD can't be in Alloy then more niche stuff (like for example Solaris, illumos, OpenBSD, NetBSD, etc.) sure can't. I was actually looking into doing some porting work to Solaris / illumos for Alloy.

**Comment by wildum** [comment]
I agree with @ptodev, as long as there is no massive blocker coming from an upstream update (Prometheus or Otel), then it should be fine to keep the FreeBSD builds

**Comment by wildum** [comment]
Closing the issue because we decided to keep FreeBSD support
