### ISSUE TITLE
Unable to use components with some nested blocks

### ISSUE THREAD

**Issue by nickelghost** [grafana/alloy#1578]
### What's wrong?

Hello, we're currently migrating to Alloy from Grafana Agent. We've reworked our modules to use the new syntax, but we're getting issues with nested blocks, such as `Error: mimir:84:3: nested blocks not supported here`. What's strange is that there are a lot of nested blocks that don't cause us any issues. For example:
```
declare "mimir" {
	// several different blocks

	prometheus.remote_write "this" {
		endpoint { // this does not cause any issues at all
			url = env("MIMIR_URL")

			headers = {
				"x-scope-orgid" = env("CLUSTER_NAME"),
			}

			basic_auth {
				username = env("MIMIR_USERNAME")
				password = env("MIMIR_PASSWORD")
			}
		}

		external_labels = {
			project     = env("PROJECT_NAME"),
			cluster     = env("CLUSTER_NAME"),
			__replica__ = env("KUBE_POD_NAME"),
		}
	}

	mimir.rules.kubernetes "this" {
		address = env("MIMIR_RULER_URL")

		tenant_id = env("CLUSTER_NAME")

		basic_auth { // offending line
			username = env("MIMIR_USERNAME")
			password = env("MIMIR_PASSWORD")
		}
	}
}
```

This also happens in the main config and with different ordering, for example:
```
mimir.rules.kubernetes "this" {
	address = env("MIMIR_RULER_URL")
	basic_auth {
		username = env("MIMIR_USERNAME")
		password = env("MIMIR_PASSWORD")
	}
	tenant_id = env("CLUSTER_NAME")
}
```

The issue also occurred for us with `pyroscope.write`'s `endpoint` block and `loki.write`'s `endpoint` block.

### Steps to reproduce

Use `mimir.rules.kubernetes` with `basic_auth`, `pyroscope.write` with `endpoint` or `loki.write` with `endpoint`.

### System information

GKE, deployed via helm chart

### Software version

Alloy 1.3.1, Helm Chart 0.6.1

**Comment by wildum** [comment]
hi, the problem I see with your config is that you are naming the custom component "mimir" but you also use a core component that's named "mimir": `mimir.rules.kubernetes`. When this happens, the custom component will shadow the core component but because you use it in the same declaration you should get a self reference error: Error: -: self reference: declare.mimir

what exact error did you get? is it solved by changing the name of the custom component?

**Comment by nickelghost** [comment]
Hi @wildum , I did not get any self reference error - only the ones showed and in the cases of loki and pyroscope, a `.receiver` not found error that was due to the `write` component failing.

Renaming the module and the component to something else was one of the first things I tried. It didn't work back then, but it does work now - perhaps there was an error on my part. Thanks for the help.

Nonetheless, the error was misleading and I don't think I've seen any mention of that requirement in the docs, so I think that the issue is still relevant.

**Comment by wildum** [comment]
Yeah I agree that there is room for improvement in the error handling. Could you share the full config that you had before please? Because I'm not getting this error with the snipped that you shared above

**Comment by wildum** [comment]
Thanks, I could generate the same error, I think that it comes from the fact that it was taking the `mimir.rules.kubernetes` has a custom component because of the `import.file "mimir"` and it was unhappy because the custom components don't have nested blocks in their blocks (the declare statement have nested blocks but not the custom component itself).
Anyway, sorry that the error was confusing, we should improve that

**Comment by nickelghost** [comment]
No worries, I'm glad we could figure it out!

My suggestion would be to add a warning block to the documentation as well.

**Comment by wildum** [comment]
Sounds reasonable, I created a PR for the doc: https://github.com/grafana/alloy/pull/1581
