### ISSUE TITLE
last line missed if no CR/LF

### ISSUE THREAD

**Issue by yosiasz** [grafana/alloy#1678]
### What's wrong?

Greetings

loving alloy! when you have a list of entries in a log file, the last line is skipped if it does not have a CR/LF 

Thanks

### Steps to reproduce

1. create a log file with 4 lines of any type of log data
2. an alloy config that reads file and processes this file

notice last line is missed in the echo section of the spun up alloy docker

Thanks

### System information

docker image of alloy

### Software version

alloy

### Configuration

```
loki.source.file "files" {
  targets    = [
    {__path__ = "/tmp/juicy.log"},
  ]
  forward_to = [loki.echo.debug.receiver]
}

loki.echo "debug" { }
```

```

#podman-compose up -d --force-recreate
version: "3"
networks:
  alloy:
services:
  alloy:
    image: grafana/alloy:latest
    ports:
      - 12345:12345
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./data/sample.log:/tmp/juicy.log
      
    command: [
          "run",
          "--server.http.listen-addr=0.0.0.0:12345",
          "--storage.path=/var/lib/alloy/data",
          "/etc/alloy/config.alloy",
        ]      
    #"--stability.level=public-preview",    xperimental, public-preview, generally-available
    networks:
      - alloy
```

### Logs

16:50:24.431 food=bar
16:51:24.432 food=bar
16:52:24.433 food=bar
16:53:24.434 food=bar

**Comment by yosiasz** [comment]
@clayton-cornell can you check this out please?

**Comment by yosiasz** [comment]
@clayton-cornell sorry :) maybe you are just docs

**Comment by clayton-cornell** [comment]
No worries. I have taken a look. I don't think this is directly a docs issue with the Alloy docs. I've poked the dev team to see if they can take a look. It might take a day or two (or four) to get a reply.

**Comment by clayton-cornell** [comment]
Hi @yosiasz  It turns out it's something I can resolve in documentation. It's expected behaviour.  You are reading line-oriented log entries. New entries are forwarded whenever a line ends with the \n character; otherwise the component would not know whether the line is completed and it should be forwarded as a long entry, or if there will be more content coming in.  See also: https://github.com/grafana/alloy/issues/451

I'll add this to my ToDo list and try to get something added into the documentation.
