### ISSUE TITLE
Support otel-collector bearer token filename

### ISSUE THREAD

**Issue by garyiwu** [grafana/alloy#1988]
### Request

The otel-collector bearertokenauthextension (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/bearertokenauthextension) supports specifying either a hard-coded `token` or a `filename` to read short-lived tokens from.  

The Alloy `otelcol.auth.bearer` component currently only supports the hard-coded `token`, making it difficult to use short-lived bearer tokens.

The request is to add support for specifying a `filename` to read short-lived tokens from, maybe in the following config form:
```
otelcol.auth.bearer "LABEL" {
  filename = "/path/to/file"
}
```

For comparison, both `loki.write` and `prometheus.remote_write` already support a `bearer_token_file` parameter in their endpoint blocks, making it very easy to use short-lived tokens there.

### Use case

Need a way to specify the use of a short-lived bearer token for use in otelcol exporters.

**Comment by wildum** [comment]
Thanks for reporting this, this seems to be an oversight in Alloy because I don't see why we could not support this. I'm adding it to the next release roadmap and as a good first issue in case someone wants to pick it up

**Comment by ravishankar15** [comment]
Hi Team, I would like to work on this issue I will raise a PR for this in this week. Can you tag it to me ?

**Comment by wildum** [comment]
That's a good point, I missed this comment. IMO we should map as close as possible to the upstream components to make it easy for the users to switch collectors. @ptodev since you originally made that comment, do you think that we should map it or do you think that we should hint better to the users that they should use the local.file component?

**Comment by wildum** [comment]
These are valid points but I also see other advantages of using the attribute besides the config converters:
- consistency with upstream (switching between one and the other is easier and the behavior is guaranteed to be the same. It makes it less vendor lock-in)
- the pipeline is simpler because you don't need an additional component
- you can still use the `local.file` component instead of the attribute (we can document that both are possible)

@garyiwu also made a good point that loki.write, prometheus.remote_write and prometheus.write.queue have a file arg for auth

**Comment by ptodev** [comment]
If people see value in having such arguments, I don't mind adding them. It will almost certainly be necessary to add them in later on, unless we want to make the config converters more complicated.

I'm aware that `prometheus.remote_write` has this sort of argument :) I had to use it the other day, and had the same issue as what I mentioned earlier - I couldn't tell how often that file is read by the component, whether it's only on startup or periodically... it's not documented in our docs and also not in the Prometheus docs.

**Comment by wildum** [comment]
I created an issue to improve the doc for this: https://github.com/grafana/alloy/issues/2188

@ravishankar15 you can move forward with the implementation of this attribute. Make sure to document that the local.file component can be used as an alternative to retrieve the password

**Comment by mattdurham** [comment]
Jumping in, not a fan of adding the file_name. We have been actively avoiding having file paths in the components. It does make the config converter slightly harder but makes the core component easier to code and use. IE there is only on path in. It also is likely easier to understand, like mentioned how is the file read, whereas local.file has specific documentation around that.

**Comment by ravishankar15** [comment]
Hey @wildum No problem, I have updated the PR with just doc changes !

**Comment by thampiotr** [comment]
Closing as it is solved with docs.
