### ISSUE TITLE
base64 encode function

### ISSUE THREAD

**Issue by ruben-janssens** [grafana/alloy#2048]
### Request

Extend the standard library encoding with a to_base64 function.

### Use case

We want to dynamically add a tenant id to the OTLP exporter but the exporter only supports 1 auth option and our endpoint is also protected with basic auth. We can manually add the Authentication header when we have a function to base64 encode the content.

**Comment by ruben-janssens** [comment]
Just as a side node base64 encode is actually not enough, it needs to be url safe base64 encoding. :)

**Comment by ravishankar15** [comment]
Hey, For adding to the headers we can use an alloy attribute and use `from_base64` function of standard library and use that attribute to header i believe ? I am not sure what change needed here since we have from_base64 as mentioned by Wildum. Do we need a separate encoding for url safe ?  Can someone help me with clarification. I can work on this issue

**Comment by ruben-janssens** [comment]
Hi @ravishankar15, thanks for willing to take up this issue :) . The `from_base64` only decodes a base64 encoded string. To add a Authentication header we need to base64 url safe encode the username and password concatenated with a `:`. Currently there is no other way to achieve basic authentication in combination with a tenant id.

**Comment by ruben-janssens** [comment]
@ravishankar15 Thanks fir the implementation! I will close this issue then because our needs are resolved :)
