### ISSUE TITLE
Allow helm chart to load all river files in volumemount

### ISSUE THREAD

**Issue by fculpo** [grafana/alloy#228]
### Request

Helm chart should be able to run agent with only a folder path, hence loading all river files in the configmap (mounted as files in /etc/agent)

This is already available in the cli: https://github.com/grafana/agent/pull/5228

This line could be easily changed with a value for loading a file or just a folder: https://github.com/grafana/agent/blob/b691a44b47b3d443cf9fa462190069ed5ff5b98f/operations/helm/charts/grafana-agent/templates/containers/_agent.yaml#L8

### Use case

I'm trying to have a main config.river and other river files that would be loaded on the fly (a la terraform) so that any environment/cluster can add components.

Modules are not helping as they still need to be declared for loading in the main config.river. If I don't want this module in some cluster, that will lead to errors or tedious overrides.

**Comment by thampiotr** [comment]
Hi @fculpo, thanks for opening this issue! We have recently adopted this [proposal process.](https://github.com/grafana/alloy/blob/main/docs/design/908-proposal-process.md) and since this is a user-facing change to a helm chart which we'll need to keep backwards compatible, I think it should follow it. I'm personally in favour of this feature, but we may want to agree on exactly how this feature should be exposed to users in the helm chart config. For example, I wonder if we should support loading multiple config maps, or a single config map with multiple files in it. We want to strike the right balance between flexibility and clarity of configuration. So maybe let's convert this issue into a proposal and get to consensus on the API details. 👍

**Comment by fculpo** [comment]
@thampiotr just opened proposal https://github.com/grafana/alloy/issues/1176

Should we close this then ? PR too ?

**Comment by thampiotr** [comment]
We can close them both. I'll bring the proposal up with the maintainers.
