### ISSUE TITLE
Type duration "d" abbrev is not respected by alloy when reading it's config

### ISSUE THREAD

**Issue by ondrej-ivanko** [grafana/alloy#599]
### What's wrong?

Hi,

I tried to define an alloy configuration file like this:
```
loki.process "old_logs" {
  stage.drop {
    older_than = "1d"
  }
  forward_to = [loki.write.ingestor.receiver]
}
```
according the [documentation](https://grafana.com/docs/alloy/latest/concepts/configuration-syntax/expressions/types_and_values/#naming-convention) - `1d` should be valid abbreviation denoting duration of 1 day

After starting docker container with this configuration I got error captured in screenshot in attachment.
![Screenshot from 2024-04-17 18-38-05](https://github.com/grafana/alloy/assets/44980578/006037e0-a097-4063-90f5-450728730b54)

### Steps to reproduce

- create configuration for alloy
- start it in docker in any way. I used docker-compose

### System information

Fedora Linux 39 6.8.6-200.fc39.x86_64

### Software version

Grafana Alloy latest, which should be 2.9.0

### Configuration

```text
discovery.docker "stdout" {
  host = "unix:///var/run/docker.sock"
  host_networking_host = "postgis-gateway"
}

loki.source.docker "gateway_logs" {
  host = "unix:///var/run/docker.sock"
  targets = discovery.docker.stdout.targets
  forward_to = [loki.process.old_logs.receiver]
  labels = { "source" = "gw-stdout" }
}

loki.process "old_logs" {
  stage.drop {
    older_than = "1h"
  }
  forward_to = [loki.write.ingestor.receiver]
}

loki.write "ingestor" {
  endpoint {
    url = "http://loki:3100/loki/api/v1/push"
  }
}
```

### Logs

```text
In attachment
```

**Comment by tpaschalis** [comment]
Thanks for the report Ondrej! I'm on the fence personally here; I think the `d` abbreviation is more dangerous than it looks; there's [a reason](https://github.com/golang/go/issues/11473) why Go's [ParseDuration](https://pkg.go.dev/time#ParseDuration) doesn't use it; mainly because it's not really well-defined, and it invites users to think in terms of calendar time instead of durations.

For example, what happens during daylight changes when we instruct Alloy to drop logs  `older_than = "1d"`? Does it suddenly start dropping 25 hours worth of logs or 23 hours worth of logs?

So in my mind, we might be better off to clear up that in the spec and remove that line. What do you think, what's your opinion here?

**Comment by ondrej-ivanko** [comment]
Hi @tpaschalis, thb, i'm not maintainer of Grafana tools, nor work with Go, but from what I read, Go does not solve working with time very well and all it's complexities, so you want to mitigate any inconsistencies than can come up with leap time durations (day, month, year).

You should remove it from spec than, if it's not used. The only issue that would arise is that using some less granular duration would require writing it in hours and add comments for other developers eg.: `600h  # 25 days`
